### ISSUE TITLE
questions about metrics

### ISSUE THREAD

**Issue by Arlo0321** [csslc/CCSR#11]
Hi author, thanks for your team's contribution. 

I would like to ask you a question about calculating the metrics during the training process. Specifically, the training process is usually interspersed with a validation step, do you perform the computation of the evaluation metrics during the validation step, which seems to be time consuming. So I'm wondering how you schedule the evaluation during the training process?

**Comment by csslc** [comment]
Hi, thanks for your attention!
As you find, performing the inference and the evaluation is time-consuming for diffusion model-based methods, so we did not verify the performance of the model during training. We only tested once or twice during training to verify that our training code was correct.

**Comment by Arlo0321** [comment]
@csslc Thank you very much for your reply!
