### ISSUE TITLE
Question About Figure.1

### ISSUE THREAD

**Issue by wangjg33** [csslc/CCSR#16]
你好！
我看到论文中Figure.1 的左图，关于时间步和PSNR与LPISP的关系感觉很有意思，很有洞见的发现。

但是这整个迭代过程是复杂的。从1000-0的时间步上，是从纯噪音到SR的过程。其中的每一步中间结果，其实包括了两部分：图像和噪音。整个过程也就是：图像质量逐渐提高，噪音逐渐减少。我们是想评估图像质量的变化，但是噪音会干扰这个测试。

请问你测试中间步的结果，是如何减少噪音对指标的影响？

因为我测了一下两个好像都是单调的曲线哎？更够提供更多的细节吗？

**Comment by csslc** [comment]
你好！感谢你对我们的发现感兴趣。
在 model/q_sampler 中有个 _predict_xstart_from_eps 函数。输入带噪的 xt 和估计出来的噪声，可以获得对应的估计出来的无噪的 x0。
我们在Figure.1 的测试都是基于每个步数估计出来的无噪的 x0 做的。
