### ISSUE TITLE
why use one-step sampling

### ISSUE THREAD

**Issue by Harperrrr111** [csslc/CCSR#17]
很棒的工作，感谢作者分享！

有个小问题想请教一下：请问推理过程中的x_T是纯噪声吗，x_T到x_tmax这一步的作用是什么？为什么不直接用LR加对应噪声得到x_tmax, 或者x_T逐步去噪直到x_tmin?

**Comment by csslc** [comment]
你好，感谢你对我们的工作感兴趣！
推理过程中 x_T 是纯噪声。x_T 到 x_max 这一步是为了直接从 LR 图片中提取信息。因为复原和生成不同，复原中的 LR 中已经包含了很多信息，不需要再像生成任务一样每个 pixel 都'从 0 生成'。因此提取完信息以后，类比于已经达到了 diffusion process 的中间步骤。因此不需要再 x_T 逐步去噪。这样做的好处是：随机性减少了，质量更加稳定，并且还可以加速。
'LR加对应噪声得到x_tmax' 这个想法很有意思，我们目前没有做过相关的验证实验。但是我觉得，这种方法可能受 LR 退化程度影响更大。如果你有有意思的发现，欢迎进一步交流讨论！
