### ISSUE TITLE
Colab run on T4

### ISSUE THREAD

**Issue by undcloud** [csslc/CCSR#19]
Hello, this is a great work!
I can't run inference code on colab with T4
![image](https://github.com/csslc/CCSR/assets/33624574/461162fe-fdbb-43a1-8c1b-d09c5e3bf6b1)
Could you help me, please?

**Comment by undcloud** [comment]
@camenduru Could you help me, please?

**Comment by undcloud** [comment]
May occur out of Memory(System RAM, not GPU RAM)

**Comment by csslc** [comment]
Hello, thanks for your attention. According to the guidance, the High-RAM Pro Colab should be used.

**Comment by undcloud** [comment]
Thank you .
I can run code on kaggle. 

https://www.kaggle.com/code/camenduru/cc-sr
