### ISSUE TITLE
Training with your own lr data

### ISSUE THREAD

**Issue by pihchikk** [csslc/CCSR#26]
Hello, thanks a lot for your work! 

I currently work on grayscale CT-images super-resolution. As I went through both steps of the training process using pre-trained stable diffusion the results turned out to be far from desired. 
I have a dataset of paired lq and hq images that I want to use to train stage1 and stage2 models. 
Is it possible to do this in the current design with minor additions to the code? 
Will the use of a SwinIR model that was pretrained with my dataset, improve the quality of generation?

**Comment by ManuBN786** [comment]
To train on LR-HR pairs, the degradation pipeline of the RealESRGAN must be removed and the dataloader should be modified to fetch your LR-HR pairs.
