### ISSUE TITLE
Line at bottom

### ISSUE THREAD

**Issue by AIisCool** [csslc/CCSR#3]
Have noticed a line at the bottom of the images.

![image](https://github.com/csslc/CCSR/assets/92149242/4f946ced-f60c-4b43-8c7d-23260460080e)

Unsure why this happens. Using default settings.

**Comment by csslc** [comment]
Hello. The padding strategy is used in 'inference_ccsr.py' to make the input LR image size be a multiple of 64, which may be the reason of this problem. We have updated the inference code to change the padding strategy to resize strategy. You can try again and see if the problem has been solved.
