### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by czzbb** [csslc/CCSR#35]
Hello, thank you very much for your work. I wonder when the training and sampling code will be updated. The current code should be the corresponding version of the 2023 paper(v1).

**Comment by csslc** [comment]
Thank you for your reminder, we will update the code within November.

**Comment by czzbb** [comment]
Thanks~. Looking forward to your updates.

**Comment by levihsu** [comment]
> Thank you for your reminder, we will update the code within November.

@csslc Hi, have you updated the code and model weights? Thanks for your great work.

**Comment by csslc** [comment]
Thank you for your interest! The CCSR-v2 code and model have been updated. We look forward to your feedback!
