### ISSUE TITLE
About the set of T and the efficient one-step diffusion model

### ISSUE THREAD

**Issue by ptang-2024** [csslc/CCSR#36]
非常棒的工作，建议requirement.txt文件中把package的版本号列一下，有些包升级过，直接pip install -r requirements.txt之后跑程序会报错。
    我测试过把图像从512x512超分到2048x2048，用的显卡是48G的A6000，结果挺不错的，但是每张图的infer时间基本在10min左右，如果能把时间缩短一下就更好了。
    目前比较困惑的有两点，一个是对最大步数T的选择，v1版paper(也是目前code对应的版本)令T=45，但v2版中T降到了6，请问是直接改超参重新训练还是...?
    另一个是单步扩散，如果time cost主要由扩散过程导致，直接从xT得到x0_bar应该还能进一步缩短时间，请问更新后的code会涉及这一部分吗:)
   抱歉对stable diffusion还不太熟悉，本打算自己改改来着，code看起来着实有点吃力，只能过来求助辣，非常感谢！

**Comment by csslc** [comment]
感谢对CCSR的关注以及提出的建议！近期我会把 V1 和 V2 版本的代码重新更新。
V2 版本是重新训练的，具体训练方式可以参照 V2 版本的 Sec. III-D 这一部分。主要需要注意的是：在 stage 2 的训练过程，我们将x_0<-T_bar 作为decoder的输入。
在单步扩散中，我们是从 x_T 直接得到了 x0_bar 的。后续更新的 V2 版本代码会有这部分的具体实现。

**Comment by csslc** [comment]
感谢关注。CCSR-v2的代码和模型现已更新，欢迎下载并尝试使用！
