### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Module

### ISSUE THREAD

**Issue by levihsu** [csslc/CCSR#37]
Hi, I met this error when trying to train stage2 model following your instruction:

RuntimeError: Error(s) in loading state_dict for Module:
        Unexpected key(s) in state_dict: "model.mask_token", "model.blocks.0.ls1.gamma", "model.blocks.0.ls2.gamma", "model.blocks.1.ls1.gamma", "model.blocks.1.ls2.gamma", "model.blocks.2.ls1.gamma", "model.blocks.2.ls2.gamma", "model.blocks.3.ls1.gamma", "model.blocks.3.ls2.gamma", "model.blocks.4.ls1.gamma", "model.blocks.4.ls2.gamma", "model.blocks.5.ls1.gamma", "model.blocks.5.ls2.gamma", "model.blocks.6.ls1.gamma", "model.blocks.6.ls2.gamma", "model.blocks.7.ls1.gamma", "model.blocks.7.ls2.gamma", "model.blocks.8.ls1.gamma", "model.blocks.8.ls2.gamma", "model.blocks.9.ls1.gamma", "model.blocks.9.ls2.gamma", "model.blocks.10.ls1.gamma", "model.blocks.10.ls2.gamma", "model.blocks.11.ls1.gamma", "model.blocks.11.ls2.gamma". 
        size mismatch for model.pos_embed: copying a param with shape torch.Size([1, 1370, 384]) from checkpoint, the shape in current model is torch.Size([1, 197, 384]).
        size mismatch for model.patch_embed.proj.weight: copying a param with shape torch.Size([384, 3, 14, 14]) from checkpoint, the shape in current model is torch.Size([384, 3, 16, 16]).

It seems to be a size mismatch in the DINO model. Could you please have a look? Thanks in advance~

**Comment by csslc** [comment]
Hello, could you help identify the source of this error? Specifically, which file it originates from and what is the exact line within the file?

**Comment by Night1099** [comment]
I get this as well, when starting stage2 train here is full error readout

https://pastebin.com/Aem0JKUr

 or 

https://www.codebin.cc/code/cm4osna4k0001mk028iocgr72:2XHpvo6t2GhTXpqdR4cAMCcmWpZ8PWpZa4DfDFSwbGUz

**Comment by Night1099** [comment]
> Hello, could you help identify the source of this error? Specifically, which file it originates from and what is the exact line within the file?

I get this as well, when starting stage2 train here is full error readout

https://pastebin.com/Aem0JKUr

or

https://www.codebin.cc/code/cm4osna4k0001mk028iocgr72:2XHpvo6t2GhTXpqdR4cAMCcmWpZ8PWpZa4DfDFSwbGUz

**Comment by levihsu** [comment]
> Hello, could you help identify the source of this error? Specifically, which file it originates from and what is the exact line within the file?

@csslc The complete error message is as follows:

Traceback (most recent call last):
  File "CCSR/train_ccsr_stage2.py", line 713, in <module>
    discriminatornet = ProjectedDiscriminator(c_dim=384).train()
  File "CCSR/ADD/models/discriminator.py", line 140, in __init__
    self.dino = DINO()
  File "CCSR/ADD/models/discriminator.py", line 117, in __init__
    reload_model_(self.model, torch.load('preset/models/dino/dino_deitsmall16_pretrain.pth'))
  File "CCSR/ADD/utils/util_net.py", line 136, in reload_model_
    model.load_state_dict(ckpt, True)
  File "/opt/conda/envs/ccsr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Module:
        Unexpected key(s) in state_dict: "model.mask_token", "model.blocks.0.ls1.gamma", "model.blocks.0.ls2.gamma", "model.blocks.1.ls1.gamma", "model.blocks.1.ls2.gamma", "model.blocks.2.ls1.gamma", "model.blocks.2.ls2.gamma", "model.blocks.3.ls1.gamma", "model.blocks.3.ls2.gamma", "model.blocks.4.ls1.gamma", "model.blocks.4.ls2.gamma", "model.blocks.5.ls1.gamma", "model.blocks.5.ls2.gamma", "model.blocks.6.ls1.gamma", "model.blocks.6.ls2.gamma", "model.blocks.7.ls1.gamma", "model.blocks.7.ls2.gamma", "model.blocks.8.ls1.gamma", "model.blocks.8.ls2.gamma", "model.blocks.9.ls1.gamma", "model.blocks.9.ls2.gamma", "model.blocks.10.ls1.gamma", "model.blocks.10.ls2.gamma", "model.blocks.11.ls1.gamma", "model.blocks.11.ls2.gamma". 
        size mismatch for model.pos_embed: copying a param with shape torch.Size([1, 1370, 384]) from checkpoint, the shape in current model is torch.Size([1, 197, 384]).
        size mismatch for model.patch_embed.proj.weight: copying a param with shape torch.Size([384, 3, 14, 14]) from checkpoint, the shape in current model is torch.Size([384, 3, 16, 16]).

**Comment by csslc** [comment]
This error was caused by the file dino_deitsmall16_pretrain.pth becoming corrupted during the transfer process. I have re-uploaded the file; please download it again and check if the issue has been resolved.

**Comment by Night1099** [comment]
> This error was caused by the file dino_deitsmall16_pretrain.pth becoming corrupted during the transfer process. I have re-uploaded the file; please download it again and check if the issue has been resolved.

Thank you!
