### ISSUE TITLE
Question about LPIPS loss in stage2 training

### ISSUE THREAD

**Issue by levihsu** [csslc/CCSR#40]
Hi, I noticed that the code involving LPIPS in stage2 training is commented, e.g.,
https://github.com/csslc/CCSR/blob/c5f7d4e37b191473028be2777f35f355af195d36/train_ccsr_stage2.py#L1127
Does that mean the LPIPS loss is unnecessary for training VAE decoder? Thanks in advance~

**Comment by csslc** [comment]
Apologies for the mistake. Using LPIPS loss is necessary since it can help stabilize adversarial training. 
We have updated the codes for stage 2 training.
