### ISSUE TITLE
OSError: Error no file named scheduler_config.json found in directory preset/models/pre-trained_controlnet/

### ISSUE THREAD

**Issue by ManuBN786** [csslc/CCSR#41]
I downloaded the models from the drive link and tried to predict on some images using command: 

 python test_ccsr_tile.py --pretrained_model_path preset/models/pre-trained_controlnet/ --controlnet_model_path preset/models/controlnet/ --vae_model_path preset/models/vae/ --baseline_name ccsr-v2 --image_path /home/manu/PycharmProjects/m-rBCR/cv_imgs/ --output_dir expirements/ --sample_method ddpm --num_inference_steps 1 --t_min 0.0 --start_point lr --start_steps 999 --process_size 512 --guidance_scale 1.0 --sample_times 1 --use_vae_encode_condition --upscale 1

but I got this error:
![error](https://github.com/user-attachments/assets/d544b598-5f71-40ac-bbb5-40bb46403eb7)

If I rename the config.json to scheduler_config.json, I get this error :
![error2](https://github.com/user-attachments/assets/d2399f02-6312-4081-b9b4-b43ef7fca5ca)

How to fix this please?

**Comment by ManuBN786** [comment]
I downloaded from https://huggingface.co/stabilityai/stable-diffusion-2-base

and then I run:

--pretrained_model_path /home/manu/PycharmProjects/AddSR/preset/models/stable-diffusion-2-base

it works fine even for 1X SR now with command: 

python test_ccsr_tile.py --pretrained_model_path /home/manu/PycharmProjects/AddSR/preset/models/stable-diffusion-2-base --controlnet_model_path preset/models --vae_model_path preset/models --baseline_name ccsr-v2 --image_path /home/manu/PycharmProjects/MHCA-main/train_valid/test_wf_small_png/ --output_dir expirements/ --sample_method ddpm --num_inference_steps 1 --t_min 0.0 --start_point lr --start_steps 999 --process_size 128 --guidance_scale 1.0 --sample_times 1 --use_vae_encode_condition --upscale 1

**Comment by csslc** [comment]
Hello, the --pretrained_model_path sholud be preset/models/stable-diffusion-2-1-base, which you can download from [HuggingFace](https://huggingface.co/stabilityai/stable-diffusion-2-1-base).
