### ISSUE TITLE
Can't Run

### ISSUE THREAD

**Issue by wodsoe** [csslc/CCSR#42]
File "E:\AI\ccsr2\CCSR-CCSR-v2.0\models\controlnet.py", line 776, in forward
    controlnet_cond = self.condition_conv_in(vae_encode_condition_hidden_states)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Soft\Miniconda\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Soft\Miniconda\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Soft\Miniconda\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Soft\Miniconda\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
TypeError: conv2d() received an invalid combination of arguments - got (NoneType, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, tuple of ints padding = 0, tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, str padding = "valid", tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)

**Comment by csslc** [comment]
Hello! It looks like the 'use_vae_encode_condition' setting has not been enabled. Please ensure it is set to 'true'.

**Comment by wodsoe** [comment]
Thank you! 
Also, what is the difference between Controlnet and Pre-trained Controlnet, and which one should be used?
What is the difference between VAE and stable dispersion 2-1 base/VAE?

**Comment by csslc** [comment]
Pre-trained Controlnet is trained considering all timesteps (1-T), and Controlnet model is finetuned from Pre-trained Controlnet considering the given timesteps (t_min-t_max). During inference stage, you should use Controlnet model.

We finetune the VAE decoder in the stage2 of training from the pretrained SD 2-1-base VAE. During inference stage, you should use VAE model.

**Comment by wodsoe** [comment]
OK. Thank you!
