### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.devices'

### ISSUE THREAD

**Issue by zhu2bowen** [csslc/CCSR#6]
感谢你们的工作！
当我部署最新的脚本(2024-1-15）时，遇到了如题的错误。看了下脚本结构，确实也没发现utils.devices。
不知道是不是我遗漏了什么。
感谢！

**Comment by csslc** [comment]
你好！我已经重新修改了代码，请再次尝试一下看看问题有没有得到解决。
感谢你的指正！
