### ISSUE TITLE
SpacedSampler.sample_ccsr() got an unexpected keyword argument 'cond_fn'

### ISSUE THREAD

**Issue by s1mple-boy** [csslc/CCSR#7]
You use sample_ccsr in inference_ccsr.py line 71, which lead to the problem shown in the title.

Is there a name written wrong?

**Comment by csslc** [comment]
Hello, Thank you for your question!
The bug has been fixed. You can update the 'inference_ccsr.py' now, and see if the problem has been solved.

**Comment by s1mple-boy** [comment]
Thank you, I run the inference code successfully now.
